### PR TITLE
NGC and ES6 bundling

### PR DESCRIPTION
**Pull request by barbatus**
feat(NGC support): generate and include metadata.json files into the NPM.
feat(ES6 bundling): UMD bundle is used as NPM's main JS file, regular TS files  are compiled into ES2015 modules that included into the NPM as well.

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@barbatus Is it ready to be merged?

**Comment by barbatus** [comment]
@kamilkisiela Yes, I tested on Socially. Works fine.

**Comment by SamoB25** [comment]
Is this going to be released anytime soon?

**Comment by kamilkisiela** [comment]
Released

**Comment by SamoB25** [comment]
Eeeeexcellent! Thanks a bunch :)

**Pull request merged**
