### PR TITLE
Multi file support

### PR DESCRIPTION
**Pull request by alex-mazzariol**
This adds basic support for emitting as many FileDrop events as there are files in the transfer.

The code did not successfully compile with manual typings, so I also removed the reference in file-drop.ts and moved the target of tsc to es6.

### CODE REVIEW

**Comment by kamilkisiela** [comment]
Why `es6`?

**Comment by bergben** [comment]
@alex-mazzariol Why did it not compile with the tpyings? Can we get this to work? Multi-file support would be awesome.

**Comment by bergben** [comment]
I decided to do this myself quickly as I needed it. Please refer to my pull request #10 which not only allows multi-file support but also updated the whole library to current state of the art of Angular libraries.

**Comment by alex-mazzariol** [comment]
Sorry for late reply; actually I did not maintain this version, and I suppose it can be done like @bergben did, which is way better than my proposal. Closing the pull-request.

**Pull request closed without merging**
